# Generate an unique ID for each simulation in the NMRlipids databank
#
# This workflow generates a pull request with the modification of the
# README files of conflictive systems.
#
# // initially written by Fabián Suárez-Lestón

name: UpdateIDs

permissions:
   contents: write
   pull-requests: write

on:
  push:
    branches: [ "main" ]
    paths: ['Simulations/**/README.yaml']
  workflow_dispatch:

jobs:
  UpdateIDs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7

      - name: Assign new IDs
        id: newids
        run: |
          . .github/workflows/CheckIDs.sh generate
        # The sh-script writes into GITHUB_OUTPUT inside itself

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v8
        # Trigger the step only if there have been changes made to the IDs
        if: steps.newids.outputs.newids == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update simulation IDs
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: workflow_addID_PR-${{ github.sha }}
          branch-suffix: short-commit-hash
          title: Update IDs after commit ${{github.sha}}
          body: |
            Generated new IDs for duplicates or new systems at ${{ github.sha }}.
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            UpdateID
            AutoPR
            contribute:sim
          draft: false

