name: Validate Databank Integrity

permissions:
    contents: read

on:
    pull_request:
        paths: 
          - 'Molecules/**'
          - 'Simulations/**'
          - 'experiments/**'

jobs:
    Validate_Integrity:
        if: github.repository == 'comcon1/BilayerData' 
        runs-on: ubuntu-latest
        container:
            image: nmrlipids/core
            options: --user 1001:118 # run container as uid=1001,gid=118 to match the GitHub runner user
        env:
            FMDL_DATA_PATH: ${{ github.workspace }}/BilayerData
        steps:
          - name: Checkout BilayerData
            uses: actions/checkout@v7
            with:
                repository: ${{ github.event.pull_request.head.repo.full_name }}
                ref: ${{ github.event.pull_request.head.ref }}
                path: BilayerData

          - name: Checkout Databank
            uses: actions/checkout@v7
            with:
                repository: NMRlipids/FAIRMD_lipids
                ref: main
                path: Databank

          - name: Install Databank dependencies
            working-directory: "Databank"
            run: |
               pip install .

          - name: Validate Integrity
            working-directory: "Databank"
            shell: bash --noprofile --norc {0}
            run: |
              out="$(
                  python developer/validate_data.py
              )"
              status=$?

              warnings=""
              while IFS= read -r line; do
                if [[ "$line" =~ [Ee][Rr][Rr][Oo][Rr] ]]; then
                  echo "::warning::Detected error line: $line"
                  warnings+="$line"$'\n'
                fi
              done <<< "$out"

              echo "::group::Full output"
              echo $out
              echo "::endgroup::"

              [ -n "$warnings" ] || warnings="None"

              {
                echo "## README.yaml validation"
                echo
                echo "**Warnings:**"
                echo
                echo '```text'
                printf '%s' "$warnings"
                echo
                echo '```'
              } >> "$GITHUB_STEP_SUMMARY"

              exit $status

